import { createContext } from "react";

const AppContext = createContext({
  seekerPosition: 0,
  setSeekerPosition: () => {},
  sourceAndTiming: [],
  setSourceAndTiming: () => {},
  currentSourceAndTiming: [],
  setCurrentSourceAndTiming: () => {},
  effectsAndTiming: [],
  setEffectsAndTiming: () => {},
  currentEffectsAndTiming: [],
  setCurrentEffectsAndTiming: () => {},
  isPlaying: false,
  setIsPlaying: () => {},
  selectedElement: null,
  setSelectedElement: () => {},
  isSpeedChange: false,
  setIsSpeedChange: () => {},
  maxTime: "00:00:00",
  setMaxTime: () => {},
  convertToFormattedTime: () => {},
  convertToPixels: () => {},
  videoPlayerRef: null,
  seekerPositionManuallyChanged: false,
  setSeekerPositionManuallyChanged: () => {},
  zoomTimeline: null,
  setZoomTimeline: () => {},
  isSplit: null,
  setIsSplit: () => {},
  isTrim: null,
  setIsTrim: () => {},
  isTimerChanged: null,
  setIsTimerChanged: () => {},
  dataArray: null,
  setDataArray: () => {},
  aspectRatio: null,
  setAspectRatio: () => {},
  getWidthByAspectRatio: () => {},
  projectId: null,
  isExportPreview: null,
  subtitleArray: null,
  setSubtitleArray: () => {},
  subtitleStyle: null,
  setSubtitleStyle: () => {},
  mediaFiles: null,
  setMediaFiles: () => {},
  projectTitle: null,
  setProjectTitle: () => {},
  mediaBlobUrl: null,
  clearBlobUrl: () => {},
  isExportPreview: null,
  setIsExportPreview: () => {},
  isSubtitleGen: null,
  setIsSubtitleGen: () => {},
  cursorDataObj: null,
  setCursorDataObj: () => {},
  selectedZoomElement: null,
  setSelectedZoomElement: () => {},
  isRecording: null,
  setIsRecording: () => {},
  screenRecorder: null,
  cameraRecorder: null,
  screenChunks: null,
  cameraChunks: null,
  activeStreams: null,
  isRecordingCursor: null,
  setIsRecordingCursor: () => {},
  recordingStartTime: null,
  setRecordingStartTime: () => {}
});

export default AppContext;
