import React, { useContext, useEffect, useRef, useState } from "react";
import AppContext from "../../AppContext";
import { pixels } from "../../utils/PixelsPerSecondEnum";
import { notify } from "../../utils/toast";

const ZoomSettings = () => {
  const {
    cursorDataObj,
    setCursorDataObj,
    selectedZoomElement,
    setSelectedZoomElement,
    seekerPosition,
    zoomTimeline,
    sourceAndTiming,
    seekerPositionManuallyChanged,
    isPlaying,
    isSplit,
  } = useContext(AppContext);
  const [zoomLevel, setZoomLevel] = useState(1.5);
  const [clickPosition, setClickPosition] = useState({ x: 0, y: 0 });
  const currentZoomElement = cursorDataObj.find(
    (item) => item.startTime === selectedZoomElement?.id
  );
  const currentElement = sourceAndTiming.find(
    (item) =>
      item.trackNum == 4 &&
      item.newStart <= currentZoomElement?.startTime &&
      item.newEnd >= currentZoomElement?.endTime
  );
  const videoRef = useRef(null);

  const handleChangeZoomLevel = (e) => {
    const newZoomLevel = parseFloat(e.target.value);
    if (currentZoomElement) {
      const updatedCursorDataObj = cursorDataObj.map((item) => {
        if (item.startTime === currentZoomElement.startTime) {
          return {
            ...item,
            zoomLevel: newZoomLevel,
          };
        }
        return item;
      });
      setCursorDataObj(updatedCursorDataObj);
      currentZoomElement.zoomLevel = newZoomLevel;
    }
  };
  const handlePreviewClick = (e) => {
    const previewRect = e.target.getBoundingClientRect();
    const clickX = e.clientX - previewRect.left; // X coordinate of the click
    const clickY = e.clientY - previewRect.top; // Y coordinate of the click

    // Calculate zoom center as a percentage of the preview size
    const centerX = clickX / previewRect.width;
    const centerY = clickY / previewRect.height;

    setClickPosition({ x: clickX, y: clickY }); // Store position for red dot
    currentZoomElement.offset = { x: centerX, y: centerY };
    console.log("Zoom center set to:", currentZoomElement.offset);

    const updatedCursorDataObj = cursorDataObj.map((item) => {
      if (item.startTime === currentZoomElement.startTime) {
        return {
          ...item,
          offset: { x: centerX, y: centerY },
        };
      }
      return item;
    });
    setCursorDataObj(updatedCursorDataObj);
  };

  const handleAddZoom = () => {
    const currentTime = Math.floor(seekerPosition / pixels[zoomTimeline]);
    const newZoomElement = {
      startTime: currentTime,
      endTime: currentTime + 2, // Default duration of 2 seconds
      zoomLevel: 1.5,
      resizable: true,
      offset: { x: 0, y: 0 },
      isAutoGenerated: false,
    };
    console.log("Adding new zoom element:", newZoomElement);

    // Check if the zoom element already exists
    const existingZoomElement = cursorDataObj.find(
      (item) => item.startTime === newZoomElement.startTime
    );
    const existingZoomElementEnd = cursorDataObj.find(
      (item) => item.endTime === newZoomElement.endTime
    );
    if (existingZoomElement) {
      notify("Zoom element already exists at this start time", "error");
      return;
    } else if (existingZoomElementEnd) {
      notify("Zoom element needs at least 2s of space", "error");
      return;
    } else {
      // If it doesn't exist, add a new zoom element
      setCursorDataObj([...cursorDataObj, newZoomElement]);
    }
    setSelectedZoomElement(newZoomElement);
  };

  const handleDeleteZoom = () => {
    if (selectedZoomElement === null) {
      return;
    }
    const updatedCursorDataObj = cursorDataObj.filter(
      (item) => item.startTime !== selectedZoomElement.id
    );
    setCursorDataObj(updatedCursorDataObj);
    setSelectedZoomElement(null);
  };

  const clearCursorData = async () => {
    try {
      await window.electronAPI.clearAllSessions();
      setCursorDataObj([]);
      console.log("All cursor data cleared");
    } catch (error) {
      console.error("Error clearing cursor data:", error);
    }
  };

  useEffect(() => {
    if (!videoRef || !videoRef.current) {
      return;
    }
    if (currentElement === undefined) {
      return;
    }
    if (
      Math.floor(seekerPosition / pixels[zoomTimeline]) <
        currentElement.newStart ||
      Math.floor(seekerPosition / pixels[zoomTimeline]) > currentElement.newEnd
    ) {
      return;
    }
    videoRef.current.currentTime =
      Math.floor(seekerPosition / pixels[zoomTimeline]) -
      currentElement.newStart +
      currentElement.startsFrom;
  }, [seekerPositionManuallyChanged, isSplit, isPlaying, seekerPosition]);

  return (
    <div className="slidecontainer">
      <div className="media-container">
        <div
          style={{
            display: "flex",
            flexDirection: "row",
            gap: "20px",
            padding: "10px",
          }}
        >
          <label>Zoom level</label>
          <input
            type="range"
            min="1"
            max="2"
            step="0.1"
            defaultValue={zoomLevel}
            onChange={(e) => {
              setZoomLevel(e.target.value), handleChangeZoomLevel(e);
            }}
          />
          <label>{zoomLevel}</label>
        </div>
        {(!selectedZoomElement ||
          Object.keys(selectedZoomElement).length === 0) && (
          <label>
            Select a zoom element from the timeline to adjust settings
          </label>
        )}
        {selectedZoomElement &&
          Object.keys(selectedZoomElement).length > 0 &&
          !selectedZoomElement.isAutoGenerated && (
            <>
              <label>
                Click on the preview to set zoom center. (You can only see the
                preview for element in the second track)
              </label>
              <div
                onClick={handlePreviewClick}
                style={{
                  width: "290px", // Preview size
                  // aspectRatio: "16/9",
                  height: "180px",
                  marginRight: "10px",
                  border: "2px solid #ccc",
                  position: "relative",
                  overflow: "hidden",
                }}
              >
                <video
                  ref={videoRef}
                  src={currentElement?.source}
                  style={{
                    width: "100%",
                    height: "100%",
                    objectFit: "cover",
                    position: "absolute",
                    left: 0,
                    top: 0,
                  }}
                  muted
                ></video>
                {clickPosition && (
                  <div
                    style={{
                      position: "absolute",
                      top: clickPosition.y - 5,
                      left: clickPosition.x - 5,
                      width: "10px",
                      height: "10px",
                      backgroundColor: "red",
                      borderRadius: "50%",
                      pointerEvents: "none",
                    }}
                  />
                )}
              </div>
            </>
          )}
      </div>
      <div
        style={{
          marginTop: "20px",
          display: "flex",
          flexDirection: "column",
          gap: "20px",
          flex: "1",
        }}
      >
        <button
          onClick={() => handleAddZoom()}
          style={{
            backgroundColor: "#EB1AB4",
            height: "30px",
            borderColor: "transparent",
            borderRadius: "4px",
            color: "white",
            cursor: "pointer",
          }}
        >
          Add new zoom
        </button>
        <button
          onClick={() => handleDeleteZoom()}
          style={{
            backgroundColor: "#EB1AB4",
            height: "30px",
            borderColor: "transparent",
            borderRadius: "4px",
            color: "white",
            cursor: "pointer",
          }}
        >
          Delete zoom
        </button>
        <button
          onClick={() => clearCursorData()}
          style={{
            backgroundColor: "red",
            height: "30px",
            borderColor: "transparent",
            borderRadius: "4px",
            color: "white",
            cursor: "pointer",
          }}
        >
          Delete all zooms
        </button>
      </div>
    </div>
  );
};

export default ZoomSettings;
