import React, { useContext, useEffect, useState } from "react";
import { Rnd } from "react-rnd";
import AppContext from "../../AppContext";
import { pixels } from "../../utils/PixelsPerSecondEnum";
import { CiCirclePlus } from "react-icons/ci";

const ZoomTrack = ({ trackNum }) => {
  const {
    cursorDataObj,
    zoomTimeline,
    setCursorDataObj,
    selectedZoomElement,
    setSelectedZoomElement,
  } = useContext(AppContext);

  const handleDrop = () => {
    //check for overlap over 2 seconds
  };
  const handleDragStop = (id, e, data) => {
    // check for overlap over other elements
    //if not, modify the cursorDataObj, insert new position according to startTime
    const newStartTime = data.x / pixels[zoomTimeline];
    const newEndTime =
      newStartTime + (cursorDataObj[id].endTime - cursorDataObj[id].startTime);
    if (checkOverlap(newStartTime, newEndTime, id)) {
      const updatedCursorDataObj = cursorDataObj.map((item, index) => {
        if (index === id) {
          return {
            ...item,
            startTime: newStartTime,
            endTime: newEndTime,
          };
        }
        return item;
      });

      setCursorDataObj(updatedCursorDataObj);

      console.log("new cursordataobj", cursorDataObj);
    } else {
      console.log("Overlap detected, cannot move element");
      return;
    }
  };
  const handleResizeStop = (id, e, direction, ref, delta, position) => {
    // check for overlap, can resize only upto a point
    // can resize the dropped zoom element only
    let newStartTime, newEndTime;
    if (direction === "left") {
      newStartTime =
        cursorDataObj[id].startTime - delta.width / pixels[zoomTimeline];
      newEndTime = cursorDataObj[id].endTime;
    }
    if (direction === "right") {
      newStartTime = cursorDataObj[id].startTime;
      newEndTime =
        cursorDataObj[id].endTime + delta.width / pixels[zoomTimeline];
    }
    console.log("newStartTime", newStartTime, "newEndTime", newEndTime, delta);

    if (checkOverlap(newStartTime, newEndTime, id)) {
      const updatedCursorDataObj = cursorDataObj.map((item, index) => {
        if (index === id) {
          return {
            ...item,
            startTime: newStartTime,
            endTime: newEndTime,
          };
        }
        return item;
      });

      setCursorDataObj(updatedCursorDataObj);
      console.log("new cursordataobj", cursorDataObj);
    } else {
      console.log("Overlap detected, cannot resize element");
      return;
    }
  };
  const checkOverlap = (startTime, endTime, index) => {
    // Check if the new time range overlaps with any existing ranges
    return cursorDataObj.some((item, _index) => {
      // Skip the current item being checked
      if (_index === index) return true;

      return (
        (startTime > item.endTime && endTime > item.endTime) ||
        (startTime < item.startTime && endTime < item.startTime)
      );
    });
  };

  return (
    <div
      className="track"
      id={`track-${trackNum}`}
      onDragOver={(e) => e.preventDefault()}
      onDrop={(e) => {
        handleDrop(e);
      }}
      style={{
        backgroundColor: "#892fff",
      }}
    >
      {cursorDataObj.map((m, index) => (
        <Rnd
          key={m.startTime}
          default={{
            x: m.startTime * pixels[zoomTimeline],
            y: 0,
          }}
          size={{
            width: Math.abs(m.endTime - m.startTime) * pixels[zoomTimeline],
            height: 40,
          }}
          bounds={`#track-${trackNum}`}
          enableResizing={{
            top: false,
            bottom: false,
            left: m.resizable ? true : false,
            right: m.resizable ? true : false,
          }}
          onResizeStop={(e, direction, ref, delta, position) => {
            handleResizeStop(index, e, direction, ref, delta, position);
          }}
          onDragStop={(e, data) => {
            handleDragStop(index, e, data);
          }}
        >
          <div
            id={index}
            className="track-video"
            style={{
              width: `${
                Math.abs(m.endTime - m.startTime) * pixels[zoomTimeline]
              }px`,
              height: "90%",
              borderRadius: "3px",
              position: "absolute",
              border:
                selectedZoomElement?.id === m.startTime
                  ? "2px solid red"
                  : "2px solid white",
              color: "white",
              backgroundColor: m.isAutoGenerated
                ? "rgba(66 184 199, 0.5)"
                : "#EB1AB4",
            }}
            onClick={() =>
              setSelectedZoomElement({
                id: m.startTime,
                isAutoGenerated: m.isAutoGenerated,
              })
            }
          >
            <CiCirclePlus color="black" size={18}/>
          </div>
        </Rnd>
      ))}
    </div>
  );
};

export default ZoomTrack;
