const path = require("path");
const {
  app,
  BrowserWindow,
  ipcMain,
  screen,
  session,
  globalShortcut,
  desktopCapturer,
  shell,
} = require("electron");
const { autoUpdater } = require("electron-updater");
const { URL } = require("url");
const dotenv = require("dotenv");
dotenv.config({ path: path.join(__dirname, "./.env") });

const isDev = !app.isPackaged;

let isRecordingClicks = false;
let intervalId = null;
let cursorDataObj = [];
let cursorData = [];
let _recordingStartTime = null;
let recordingStartTimestamp = null;

ipcMain.on("toggle-recording", (event, recordingStartTime) => {
  console.log(
    "Toggle recording called, current state:",
    isRecordingClicks,
    recordingStartTime
  );

  if (isRecordingClicks) {
    // Stop recording
    console.log("Stopping recording...");
    const sessionData = stopRecording();
    if (sessionData) {
      event.reply("recording-stopped", sessionData);
    } else {
      event.reply("recording-cancelled");
    }
  } else {
    // Start recording
    console.log("Starting recording...");
    startRecording(recordingStartTime);
    event.reply("recording-started");
  }
});

ipcMain.on("force-stop-recording", (event) => {
  console.log("Force stop recording called");
  if (isRecordingClicks) {
    const sessionData = stopRecording();
    event.reply("recording-force-stopped", sessionData || cursorDataObj);
  } else {
    event.reply("recording-force-stopped", cursorDataObj);
  }
});

function startRecording(recordingStartTime) {
  console.log("Starting recording with start time:", recordingStartTime);

  _recordingStartTime = recordingStartTime;
  recordingStartTimestamp = Date.now(); // Add this line
  isRecordingClicks = true;
  cursorData = []; // Reset cursor data for new recording

  // Immediately capture first cursor position
  const { x, y } = screen.getCursorScreenPoint();
  const timestamp = (Date.now() - _recordingStartTime) / 1000; // Convert to seconds with decimals
  cursorData.push({ x, y, timestamp });
  console.log("Initial cursor position captured:", { x, y, timestamp });

  // Change interval to 100ms for smooth tracking
  intervalId = setInterval(() => {
    if (!isRecordingClicks) {
      clearInterval(intervalId);
      return;
    }

    const { x, y } = screen.getCursorScreenPoint();
    const timestamp = (Date.now() - _recordingStartTime) / 1000; // Convert to seconds with decimals
    console.log("Cursor position captured:", { x, y, timestamp });

    cursorData.push({ x, y, timestamp });
  }, 500);
}

function stopRecording() {
  if (!isRecordingClicks) {
    console.log("Not recording, nothing to stop");
    return null;
  }

  const actualRecordingDuration = Date.now() - recordingStartTimestamp;
  isRecordingClicks = false;

  if (intervalId) {
    clearInterval(intervalId);
    intervalId = null;
  }

  // Check for minimum recording duration and minimum data points
  if (cursorData.length === 0) {
    console.log("No cursor data collected, skipping session");
    cursorData = [];
    return null;
  }

  if (actualRecordingDuration < 200) {
    console.log("Recording too short (< 200ms), skipping session");
    cursorData = [];
    return null;
  }

  // Create session with correct structure for MediaPlayer
  const recordingSession = {
    startTime: cursorData[0].timestamp,
    endTime: cursorData[cursorData.length - 1].timestamp,
    cursorData: [...cursorData],
    createdAt: new Date().toISOString(),
    zoomLevel: 1.5,
    isAutoGenerated: true,
  };
  const relativeCursorData = recordingSession.cursorData.map((data) => {
    return {
      ...data,
      timestamp: data.timestamp - recordingSession.startTime, // Make timestamps relative to start time
    };
  });
  recordingSession.cursorData = relativeCursorData;
  cursorDataObj.push(recordingSession);
  console.log("Recording session added. Total sessions:", cursorDataObj.length);
  console.log("Session data:", recordingSession);

  // Reset for next recording
  cursorData = [];
  recordingStartTimestamp = null;

  return recordingSession;
}
// Handle desktop capturer requests
ipcMain.handle("get-desktop-sources", async () => {
  const sources = await desktopCapturer.getSources({
    types: ["window", "screen"],
    thumbnailSize: { width: 150, height: 150 },
  });
  return sources.map((source) => ({
    id: source.id,
    name: source.name,
    thumbnail: source.thumbnail.toDataURL(),
  }));
});
ipcMain.handle("resize-window", async (event, { width, height }) => {
  const win = BrowserWindow.fromWebContents(event.sender);
  console.log("Resizing window to:", width, height, win);

  if (win) {
    win.setBounds(width, height);
    win.center();
    win.show();
  }
});
ipcMain.handle("get-all-sessions", () => {
  if (intervalId) {
    clearInterval(intervalId);
  }

  const { width: screenWidth, height: screenHeight } =
    screen.getPrimaryDisplay().bounds;

  // Normalize coordinates and ensure correct structure
  const normalizedCursorDataObj = cursorDataObj.map((session) => {
    return {
      ...session,
      cursorData: session.cursorData.map((data) => ({
        ...data,
        x: data.x / screenWidth, // Normalize x to screen width
        y: data.y / screenHeight, // Normalize y to screen height
      })),
    };
  });

  console.log("Returning normalized cursor data:", normalizedCursorDataObj);
  return normalizedCursorDataObj;
});

// Clear all sessions (useful for testing)
ipcMain.handle("clear-all-sessions", () => {
  cursorDataObj = [];
  cursorData = [];
  console.log("All cursor sessions cleared");
  return true;
});

// Add this near the top of your main.cjs, before app.whenReady()
if (process.defaultApp) {
  if (process.argv.length >= 2) {
    app.setAsDefaultProtocolClient("rookieclip", process.execPath, [
      path.resolve(process.argv[1]),
    ]);
  }
} else {
  app.setAsDefaultProtocolClient("rookieclip");
}

// Handle protocol for Windows
app.on("second-instance", (event, commandLine, workingDirectory) => {
  // Someone tried to run a second instance, we should focus our window instead
  const win = BrowserWindow.getAllWindows()[0];
  if (win) {
    if (win.isMinimized()) win.restore();
    win.focus();
  }

  // Handle the protocol URL on Windows
  const url = commandLine.find((arg) => arg.startsWith("rookieclip://"));
  if (url) {
    handleProtocolUrl(url);
  }
});

// Handle protocol for macOS
app.on("open-url", (event, url) => {
  event.preventDefault();
  handleProtocolUrl(url);
});

// Extract the protocol handling logic
function handleProtocolUrl(url) {
  console.log("Received URL:", url);

  const win = BrowserWindow.getAllWindows()[0];
  if (!win) {
    console.log("No window found");
    return;
  }

  try {
    const myURL = new URL(url);
    const code = myURL.searchParams.get("code");
    const error = myURL.searchParams.get("error");

    if (error) {
      console.error("OAuth error:", error);
      win.webContents.send("auth-error", error);
      return;
    }

    if (code) {
      console.log("Received auth code:", code);

      // Exchange the code for an access token
      exchangeCodeForToken(code)
        .then((tokenResponse) => {
          console.log("Token exchange successful");
          win.webContents.send("auth-success", tokenResponse.access_token);
        })
        .catch((tokenError) => {
          console.error("Token exchange failed:", tokenError);
          win.webContents.send("auth-error", "Token exchange failed");
        });

      // Bring the window to focus
      win.show();
      win.focus();
    }
  } catch (parseError) {
    console.error("Error parsing URL:", parseError);
    win.webContents.send("auth-error", "Invalid callback URL");
  }
}
function createWindow() {
  const win = new BrowserWindow({
    width: 1200,
    height: 800,
    icon: path.join(__dirname, "../public/assets", "rookieclip3.ico"),
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      enableRemoteModule: true,
      webSecurity: false,
      allowRunningInsecureContent: true,
      experimentalFeatures: true,
      preload: path.join(__dirname, "preload.js"),
      hardwareAcceleration: true,
      // Optimize for animations
      backgroundThrottling: false,
    },
  });
  win.removeMenu();
  win.webContents.on("before-input-event", (event, input) => {
    const isRefresh =
      (input.control || input.meta) && input.key.toLowerCase() === "r";

    if (isRefresh) {
      win.reload();
      event.preventDefault();
    }
  });

  isDev
    ? win.loadURL("http://localhost:5173")
    : win.loadURL("https://rookieclip.com");

  if (isDev) win.webContents.openDevTools();

  return win;
}

app.on("ready", () => {
  autoUpdater.checkForUpdatesAndNotify();
});
autoUpdater.on("update-downloaded", () => {
  autoUpdater.quitAndInstall(); // Optional: auto install
});
// Add this before app.whenReady()
const gotTheLock = app.requestSingleInstanceLock();

if (!gotTheLock) {
  app.quit();
} else {
  app.whenReady().then(() => {
    globalShortcut.register("CommandOrControl+Shift+K", () => {
      console.log("Cursor capture recording shortcut pressed");
      win.webContents.send("cursor-capture"); // ✅ Send to renderer
    });
    // Enable all permissions by default
    session.defaultSession.setPermissionRequestHandler(
      (webContents, permission, callback) => {
        console.log("Permission requested:", permission);
        callback(true);
      }
    );

    session.defaultSession.setPermissionCheckHandler(
      (webContents, permission, requestingOrigin, details) => {
        console.log("Permission check:", permission, requestingOrigin);
        return true;
      }
    );

    session.defaultSession.setDisplayMediaRequestHandler(
      (request, callback) => {
        console.log("Display media request received");
        console.log("Request details:", request);

        const displays = screen.getAllDisplays();
        console.log("Available displays:", displays.length);

        if (displays.length > 0) {
          const primaryDisplay = displays[0];
          console.log("Granting access to primary display:", primaryDisplay.id);

          callback({
            video: {
              id: `screen:${primaryDisplay.id}:0`,
              name: `Display ${primaryDisplay.id}`,
              width: primaryDisplay.bounds.width,
              height: primaryDisplay.bounds.height,
            },
            audio: "loopback",
          });
        } else {
          console.log("No displays available");
          callback({});
        }
      }
    );

    session.defaultSession.protocol.interceptStreamProtocol(
      "media-stream",
      (request, callback) => {
        console.log("Media stream protocol intercepted:", request.url);
        callback({ statusCode: 200 });
      }
    );

    const win = createWindow();

    win.webContents.on("media-started-playing", () => {
      console.log("Media started playing");
    });

    win.webContents.on("media-paused", () => {
      console.log("Media paused");
    });

    app.on("activate", () => {
      if (BrowserWindow.getAllWindows().length === 0) createWindow();
    });
  });
}
// Handle Google OAuth
ipcMain.handle("start-google-auth", async () => {
  const authUrl =
    `https://accounts.google.com/o/oauth2/v2/auth?` +
    `client_id=${process.env.GOOGLE_CLIENT_ID}&` +
    `redirect_uri=${encodeURIComponent(process.env.REDIRECT_URI)}&` +
    `response_type=code&` +
    `scope=${encodeURIComponent("openid email profile")}`;

  console.log("Opening auth URL:", authUrl);

  // Open the OAuth URL in the system's default browser
  shell.openExternal(authUrl);
});

// Function to exchange authorization code for access token
async function exchangeCodeForToken(code) {
  const tokenUrl = "https://oauth2.googleapis.com/token";

  const params = new URLSearchParams({
    client_id: process.env.GOOGLE_CLIENT_ID,
    client_secret: process.env.GOOGLE_CLIENT_SECRET,
    code: code,
    grant_type: "authorization_code",
    redirect_uri: process.env.REDIRECT_URI,
  });

  const response = await fetch(tokenUrl, {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: params,
  });

  if (!response.ok) {
    throw new Error(`Token exchange failed: ${response.statusText}`);
  }

  return await response.json();
}

app.on(
  "certificate-error",
  (event, webContents, url, error, certificate, callback) => {
    event.preventDefault();
    callback(true);
  }
);

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") app.quit();
});

app.commandLine.appendSwitch("enable-media-stream");
app.commandLine.appendSwitch("enable-usermedia-screen-capturing");
app.commandLine.appendSwitch(
  "auto-select-desktop-capture-source",
  "Entire screen"
);
app.commandLine.appendSwitch("disable-features", "VizDisplayCompositor");
app.commandLine.appendSwitch("enable-gpu-rasterization");
app.commandLine.appendSwitch("enable-oop-rasterization");
app.commandLine.appendSwitch("enable-hardware-overlays");
app.commandLine.appendSwitch("enable-features", "VaapiVideoDecoder");

// Optimize for screen recording
app.commandLine.appendSwitch("disable-background-timer-throttling");
app.commandLine.appendSwitch("disable-backgrounding-occluded-windows");
app.commandLine.appendSwitch("disable-renderer-backgrounding");
