const path = require("path");
const {
  app,
  BrowserWindow,
  ipcMain,
  screen,
  session,
  globalShortcut,
  desktopCapturer
} = require("electron");

const isDev = !app.isPackaged;
let mainWindow = null;

let isRecordingClicks = false;
let intervalId = null;
let cursorDataObj = [];
let cursorData = [];
let _recordingStartTime = null;
let recordingStartTimestamp = null;

ipcMain.on("toggle-recording", (event, recordingStartTime) => {
  console.log(
    "Toggle recording called, current state:",
    isRecordingClicks,
    recordingStartTime
  );

  if (isRecordingClicks) {
    // Stop recording
    console.log("Stopping recording...");
    const sessionData = stopRecording();
    if (sessionData) {
      event.reply("recording-stopped", sessionData);
    } else {
      event.reply("recording-cancelled");
    }
  } else {
    // Start recording
    console.log("Starting recording...");
    startRecording(recordingStartTime);
    event.reply("recording-started");
  }
});

ipcMain.on("force-stop-recording", (event) => {
  console.log("Force stop recording called");
  if (isRecordingClicks) {
    const sessionData = stopRecording();
    event.reply("recording-force-stopped", sessionData || cursorDataObj);
  } else {
    event.reply("recording-force-stopped", cursorDataObj);
  }
});

function startRecording(recordingStartTime) {
  console.log("Starting recording with start time:", recordingStartTime);

  _recordingStartTime = recordingStartTime;
  recordingStartTimestamp = Date.now(); // Add this line
  isRecordingClicks = true;
  cursorData = []; // Reset cursor data for new recording

  // Immediately capture first cursor position
  const { x, y } = screen.getCursorScreenPoint();
  const timestamp = (Date.now() - _recordingStartTime) / 1000; // Convert to seconds with decimals
  cursorData.push({ x, y, timestamp });
  console.log("Initial cursor position captured:", { x, y, timestamp });

  // Change interval to 100ms for smooth tracking
  intervalId = setInterval(() => {
    if (!isRecordingClicks) {
      clearInterval(intervalId);
      return;
    }

    const { x, y } = screen.getCursorScreenPoint();
    const timestamp = (Date.now() - _recordingStartTime) / 1000; // Convert to seconds with decimals
    console.log("Cursor position captured:", { x, y, timestamp });

    cursorData.push({ x, y, timestamp });
  }, 500); 
}

function stopRecording() {
  if (!isRecordingClicks) {
    console.log("Not recording, nothing to stop");
    return null;
  }

  const actualRecordingDuration = Date.now() - recordingStartTimestamp;
  isRecordingClicks = false;

  if (intervalId) {
    clearInterval(intervalId);
    intervalId = null;
  }

  // Check for minimum recording duration and minimum data points
  if (cursorData.length === 0) {
    console.log("No cursor data collected, skipping session");
    cursorData = [];
    return null;
  }

  if (actualRecordingDuration < 200) {
    console.log("Recording too short (< 200ms), skipping session");
    cursorData = [];
    return null;
  }

  // Create session with correct structure for MediaPlayer
  const recordingSession = {
    startTime: cursorData[0].timestamp,
    endTime: cursorData[cursorData.length - 1].timestamp,
    cursorData: [...cursorData],
    createdAt: new Date().toISOString(),
    zoomLevel: 1.5,
    isAutoGenerated: true
  };
  const relativeCursorData = recordingSession.cursorData.map((data) => {
    return{
      ...data,
      timestamp: data.timestamp - recordingSession.startTime, // Make timestamps relative to start time
    }
})
recordingSession.cursorData = relativeCursorData;
  cursorDataObj.push(recordingSession);
  console.log("Recording session added. Total sessions:", cursorDataObj.length);
  console.log("Session data:", recordingSession);

  // Reset for next recording
  cursorData = [];
  recordingStartTimestamp = null;

  return recordingSession;
}
// Handle desktop capturer requests
ipcMain.handle("get-desktop-sources", async () => {
  const sources = await desktopCapturer.getSources({
    types: ["window", "screen"],
    thumbnailSize: { width: 150, height: 150 },
  });
  return sources.map((source) => ({
    id: source.id,
    name: source.name,
    thumbnail: source.thumbnail.toDataURL(),
  }));
});
ipcMain.handle("resize-window", async (event, { width, height }) => {
  const win = BrowserWindow.fromWebContents(event.sender);
  console.log("Resizing window to:", width, height, win);
  
  if (win) {
    win.setBounds(width, height);
    win.center();
    win.show();
  }
});
ipcMain.handle("get-all-sessions", () => {
  if (intervalId) {
    clearInterval(intervalId);
  }

  const { width: screenWidth, height: screenHeight } =
    screen.getPrimaryDisplay().bounds;

  // Normalize coordinates and ensure correct structure
  const normalizedCursorDataObj = cursorDataObj.map((session) => {
    return {
      ...session,
      cursorData: session.cursorData.map((data) => ({
        ...data,
        x: data.x / screenWidth, // Normalize x to screen width
        y: data.y / screenHeight, // Normalize y to screen height
      })),
    };
  });

  console.log("Returning normalized cursor data:", normalizedCursorDataObj);
  return normalizedCursorDataObj;
});

// Clear all sessions (useful for testing)
ipcMain.handle("clear-all-sessions", () => {
  cursorDataObj = [];
  cursorData = [];
  console.log("All cursor sessions cleared");
  return true;
});

function createWindow() {
  const win = new BrowserWindow({
    width: 1200,
    height: 800,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      enableRemoteModule: true,
      webSecurity: false,
      allowRunningInsecureContent: true,
      experimentalFeatures: true,
      preload: path.join(__dirname, "preload.js"),
      hardwareAcceleration: true,
      // Optimize for animations
      backgroundThrottling: false,
    },
  });
  win.removeMenu();
    
  
  const appURL = isDev
    ? "http://localhost:5173"
    : `file://${path.join(__dirname, "../dist/index.html")}`;

  win.loadURL(appURL);

  if (isDev) win.webContents.openDevTools();

  return win;
}

app.whenReady().then(() => {
  globalShortcut.register("CommandOrControl+Shift+K", () => {
    console.log("Cursor capture recording shortcut pressed");
    win.webContents.send("cursor-capture"); // ✅ Send to renderer
  });
  // Enable all permissions by default
  session.defaultSession.setPermissionRequestHandler(
    (webContents, permission, callback) => {
      console.log("Permission requested:", permission);
      callback(true);
    }
  );

  session.defaultSession.setPermissionCheckHandler(
    (webContents, permission, requestingOrigin, details) => {
      console.log("Permission check:", permission, requestingOrigin);
      return true;
    }
  );

  session.defaultSession.setDisplayMediaRequestHandler((request, callback) => {
    console.log("Display media request received");
    console.log("Request details:", request);

    const displays = screen.getAllDisplays();
    console.log("Available displays:", displays.length);

    if (displays.length > 0) {
      const primaryDisplay = displays[0];
      console.log("Granting access to primary display:", primaryDisplay.id);

      callback({
        video: {
          id: `screen:${primaryDisplay.id}:0`,
          name: `Display ${primaryDisplay.id}`,
          width: primaryDisplay.bounds.width,
          height: primaryDisplay.bounds.height,
        },
        audio: "loopback",
      });
    } else {
      console.log("No displays available");
      callback({});
    }
  });

  session.defaultSession.protocol.interceptStreamProtocol(
    "media-stream",
    (request, callback) => {
      console.log("Media stream protocol intercepted:", request.url);
      callback({ statusCode: 200 });
    }
  );

  const win = createWindow();

  win.webContents.on("media-started-playing", () => {
    console.log("Media started playing");
  });

  win.webContents.on("media-paused", () => {
    console.log("Media paused");
  });
  
  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on(
  "certificate-error",
  (event, webContents, url, error, certificate, callback) => {
    event.preventDefault();
    callback(true);
  }
);

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") app.quit();
});

app.commandLine.appendSwitch("enable-media-stream");
app.commandLine.appendSwitch("enable-usermedia-screen-capturing");
app.commandLine.appendSwitch(
  "auto-select-desktop-capture-source",
  "Entire screen"
);
app.commandLine.appendSwitch("disable-features", "VizDisplayCompositor");
app.commandLine.appendSwitch("enable-gpu-rasterization");
app.commandLine.appendSwitch("enable-oop-rasterization");
app.commandLine.appendSwitch("enable-hardware-overlays");
app.commandLine.appendSwitch("enable-features", "VaapiVideoDecoder");

// Optimize for screen recording
app.commandLine.appendSwitch("disable-background-timer-throttling");
app.commandLine.appendSwitch("disable-backgrounding-occluded-windows");
app.commandLine.appendSwitch("disable-renderer-backgrounding");
